import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Sorodrop",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light">
      <body className={`font-montserrat antialiased`}>{children}</body>
    </html>
  )
}
